-- Migration: Initial Schema (SQLite to Postgres)

-- Games
CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Accounts
CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    start_date TEXT NOT NULL,
    start_time TEXT NOT NULL,
    request_template TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Levels
CREATE TABLE levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    event_token TEXT NOT NULL,
    level_name TEXT NOT NULL,
    days_offset INTEGER NOT NULL DEFAULT 0,
    time_spent INTEGER NOT NULL DEFAULT 0,
    is_bonus BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE(game_id, event_token, days_offset)
);

-- Purchase Events
CREATE TABLE purchase_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    event_token TEXT NOT NULL,
    is_restricted BOOLEAN NOT NULL DEFAULT FALSE,
    max_days_offset INTEGER,
    days_offset INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(game_id, event_token)
);

-- Account Level Progress
CREATE TABLE account_level_progress (
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    level_id BIGINT NOT NULL REFERENCES levels(id) ON DELETE CASCADE,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMPTZ,
    PRIMARY KEY (account_id, level_id)
);

-- Account Purchase Event Progress
CREATE TABLE account_purchase_event_progress (
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    purchase_event_id BIGINT NOT NULL REFERENCES purchase_events(id) ON DELETE CASCADE,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    days_offset INTEGER NOT NULL DEFAULT 0,
    time_spent INTEGER NOT NULL DEFAULT 0,
    completed_at TIMESTAMPTZ,
    PRIMARY KEY (account_id, purchase_event_id)
);

-- Enable Realtime for all tables
alter publication supabase_realtime add table games, accounts, levels, purchase_events, account_level_progress, account_purchase_event_progress;
